<?php

/**
 * @file
 * Contains alterations for the Hel.fi navigation.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\menu_link_content\MenuLinkContentInterface;
use Drupal\system\MenuInterface;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function helfi_navigation_theme_suggestions_menu_alter(array &$suggestions, array $variables) : void {
  if ($variables['theme_hook_original'] === 'menu__external_menu') {
    if (isset($variables['menu_type'])) {
      $suggestions[] = 'menu__external_menu__' . $variables['menu_type'];
    }
    if (
      isset($variables['attributes']['block_id']) &&
      str_contains($variables['attributes']['block_id'], 'mega_menu')
    ) {
      $suggestions[] = 'menu__external_menu__mega_menu';
    }
  }
}

/**
 * Implements hook_theme().
 */
function helfi_navigation_theme() : array {
  return [
    'menu__external_menu__fallback' => [
      'variables' => [
        'menu_name' => NULL,
        'items' => [],
        'attributes' => [],
        'menu_link_back' => [],
        'menu_link_current_or_parent' => [],
      ],
    ],
    'menu__external_menu' => [
      'variables' => [
        'menu_type' => NULL,
        'items' => [],
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_base_field_info().
 */
function helfi_navigation_entity_base_field_info(EntityTypeInterface $entity_type) : array {
  $fields = [];

  if ($entity_type->id() === 'menu_link_content') {
    $fields['lang_attribute'] = BaseFieldDefinition::create('string')
      ->setLabel(new TranslatableMarkup('Language attribute'))
      ->setDescription(new TranslatableMarkup('The "lang" attribute.'))
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE)
      ->setSetting('max_length', 10)
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
      ])
      ->setDisplayConfigurable('form', TRUE);
  }
  return $fields;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_navigation_preprocess_menu__external_menu__fallback(&$variables) : void {
  if (is_array($variables['items']) && !empty($variables['items'])) {
    foreach ($variables['items'] as &$menu_link) {
      $menu_link['next_url'] = clone $menu_link['url'];
      $menu_link['next_url']->setOption('fragment', 'menu');
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function helfi_navigation_menu_update(MenuInterface $entity) : void {
  if ($entity->id() === 'main') {
    _helfi_navigation_queue_item();
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function helfi_navigation_menu_link_content_update(MenuLinkContentInterface $entity) : void {
  if ($entity->getMenuName() === 'main') {
    _helfi_navigation_queue_item();
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function helfi_navigation_menu_link_content_insert(MenuLinkContentInterface $entity) : void {
  if ($entity->getMenuName() === 'main') {
    _helfi_navigation_queue_item();
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function helfi_navigation_menu_link_content_delete(MenuLinkContentInterface $entity) : void {
  if ($entity->getMenuName() === 'main') {
    _helfi_navigation_queue_item();
  }
}

/**
 * Create menu update queue item.
 */
function _helfi_navigation_queue_item() : void {
  if (!\Drupal::config('helfi_navigation.api')->get('key')) {
    return;
  }
  $queue = Drupal::queue('helfi_navigation_menu_queue');

  // Queue items only when queue is empty.
  if ($queue->numberOfItems() === 0) {
    foreach (\Drupal::languageManager()->getLanguages() as $language) {
      $queue->createItem($language->getId());
    }
  }
}

/**
 * Implements hook_cron().
 */
function helfi_navigation_cron() : void {
  /** @var \Drupal\helfi_navigation\CacheWarmer $warmer */
  $warmer = Drupal::service('helfi_navigation.cache_warmer');
  $warmer->warm();
}

/**
 * Implements hook_page_attachments().
 */
function helfi_navigation_page_attachments(array &$attachments) : void {
  $langcode = Drupal::languageManager()
    ->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)
    ->getId();

  // Currently only Finnish, English and Swedish have standard support.
  // Other languages should default to English external menus for now.
  if (!in_array($langcode, ['fi', 'en', 'sv'])) {
    $langcode = 'en';
  }

  /** @var \Drupal\helfi_navigation\ApiManager $apiManager */
  $apiManager = Drupal::service('helfi_navigation.api_manager');

  try {
    $attachments['#attached']['drupalSettings']['helfi_navigation'] = [
      'links' => [
        'api' => $apiManager->getUrl('js', $langcode, ['endpoint' => '/api/v1/global-mobile-menu']),
        'canonical' => $apiManager->getUrl('canonical', $langcode),
      ],
    ];
  }
  catch (\Exception) {
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 */
function helfi_navigation_form_node_form_alter(
  array &$form,
  FormStateInterface $form_state
) :void {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();
  $defaults = menu_ui_get_menu_link_defaults($node);

  if ($defaults['entity_id']) {
    $link = MenuLinkContent::load($defaults['entity_id']);

    if ($link->hasTranslation($node->language()->getId())) {
      $link = $link->getTranslation($node->language()->getId());
    }
    $defaults['content_translation_status'] = $link->get('content_translation_status')->value;
  }

  // Show menu link's 'published' field on node edit form.
  $form['menu']['content_translation_status'] = [
    '#type' => 'checkbox',
    '#title' => t('Published'),
    '#description' => t('A flag indicating whether this menu link translation is published'),
    '#default_value' => $defaults['content_translation_status'],
  ];
  $form['actions']['submit']['#submit'][] = 'helfi_navigation_form_node_form_submit';
}

/**
 * A form submit callback for helfi_navigation_form_node_form_alter().
 */
function helfi_navigation_form_node_form_submit(array $form, FormStateInterface $formState) : void {
  $values = $formState->getValue('menu');
  $node = $formState->getFormObject()->getEntity();

  if (!empty($values['entity_id'])) {
    $link = MenuLinkContent::load($values['entity_id']);

    if ($link->hasTranslation($node->language()->getId())) {
      $link = $link->getTranslation($node->language()->getId());
    }
    $link->set('content_translation_status', $values['content_translation_status'])
      ->save();
  }
}
