helfi_navigation.api:
  type: mapping
  mapping:
    key:
      type: string
    langcode:
      type: string

block.settings.external_menu_block:*:
  type: block_settings
  label: 'External menu block'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    expand_all_items:
      type: boolean
      label: 'Expand all items'
    depth:
      type: integer
      label: 'Maximum number of levels'

block.settings.external_menu_block_fallback:
  type: block_settings
  label: 'External menu block (fallback)'
  mapping:
    level:
      type: integer
      label: 'Starting level'
    expand_all_items:
      type: boolean
      label: 'Expand all items'
    depth:
      type: integer
      label: 'Maximum number of levels'

